### ISSUE TITLE
Publish publicly on npm

### ISSUE THREAD

**Issue by ajoslin** [eaze/css-reset#1]
Without access to the @eaze org, npm install throws an error that the package doesn't exist.

**Comment by bendrucker** [comment]
Done: https://www.npmjs.com/package/@eaze/css-reset

This was the important part: https://docs.npmjs.com/getting-started/scoped-packages#publishing-a-scoped-package

I think scoped packages are a good way to put code out as open source without giving the project a brand and creating the expectation that you'll adapt it for a more general audience.

**Comment by ajoslin** [comment]
:+1: agreed.
